### PR TITLE
fix(kubernetes)!: Provider updated for each watcher callback

### LINKED ISSUE #522: Provider watchers to update underlying manager
## Description

In #520 I likely introduced a non-documented behavioral regression.

Before the introduced changes, the `mcp.Server` instance recreated the `kubernetes.Provider` whenever the `reloadKubernetesClusterProvider` callback was called.
This wasn't a straightforward implementation since the callback itself was called from the `kubernetes.Provider` instance.
In the method, the `mcp.Server` teared down the active `kubernetes.Provider` and recreated it.

After the introduced changes, the `mcp.Server` instance exposes a `reloadToolsets` method that is used as a callback by the `kubernetes.Provider` watchers (`WatchTargets(reload McpReload)`).
The `mcp.Server` no longer recreates the `kubernetes.Provider` instance, which is active for the entire lifecycle of the mcp.Server.

This means that if the underlying configurations for the applicable `kubernetes.Manager` instances managed my the `kuberentes.Provider` are changed, the provider itself won't be aware of these.
Same happens in case new contexts/targets are added to the configuration.

### PR DESCRIPTION
**Pull request by manusa**
Fixes #522 
Replaces #531

The `kubernetes.Provider` watch-related functionality is restarted for each watch notification that affects its state.

### CODE REVIEW

**Comment by manusa** [comment]
Once this one is merged or the related bug is fixed we should start with the 0.0.55 release which should be stable enough.

File: pkg/kubernetes/provider_kubeconfig.go [hunk 1]
```diff
@@ -35,37 +37,44 @@ func init() {
...
 		rawConfig.CurrentContext: m, // we already initialized a manager for the default context, let's use it
 	}
 
 	for name := range rawConfig.Contexts {
 		if name == rawConfig.CurrentContext {
 			continue // already initialized this, don't want to set it to nil
 		}
-
-		allClusterManagers[name] = nil
+		p.managers[name] = nil
```
Comment (nader-ziada) [inline pkg/kubernetes/provider_kubeconfig.go:69]: would these managers have any resources that should be cleaned up

Comment (manusa) [reply pkg/kubernetes/provider_kubeconfig.go:69]: That's a good question.

We don't provide a `kubernetes.Manager`.Clean method.

The manager itself has a pointer reference to the global `config.StaticConfig` and an instance of `kubernetes.AccessControlClientset`.

The clientset has instances of the discovery client, dynamic client, and kubernetes interface. But AFAICT, none of those clients provide clean up methods.

I might have missed something, but I'd say that there's no clean up needed.
