### PR TITLE
fix(http): add CORS headers for well-known endpoints

### LINKED ISSUE #625: Investigate Well Known middleware header forwarding
Currently in https://github.com/containers/kubernetes-mcp-server/blob/main/pkg/http/wellknown.go we forward all headers (except for the "forwarded" headers) to the IdP. This was initially done to make CORS work in the OAuth flow.

We should investigate specifically which headers need to be forwarded in this flow, and only forward those.

### PR DESCRIPTION
**Pull request by manusa**
Fixes #625
Relates to #406
Relates to #624

- Stop propagating client headers to authorization server requests
- Add explicit CORS headers (Access-Control-Allow-Origin, Methods, Headers)
- Preserve backend response header propagation with CORS override
- Migrate well-known tests to testify/suite in dedicated test file
- Export kubeconfig to _output during kind cluster creation

### CODE REVIEW

File: pkg/http/wellknown.go [hunk 1]
```diff
@@ -97,7 +85,11 @@ func (w WellKnown) ServeHTTP(writer http.ResponseWriter, request *http.Request)
 			writer.Header().Add(key, value)
 		}
 	}
+	writer.Header().Set("Content-Type", "application/json")
 	writer.Header().Set("Content-Length", fmt.Sprintf("%d", len(body)))
+	writer.Header().Set("Access-Control-Allow-Origin", "*")
```
Comment (matzew) [inline pkg/http/wellknown.go:96]: nit: I guess we could encapsulate those CORS headers into some helper, like `func writeCORSHeaders` ?

File: pkg/http/http_test.go [hunk 2]
```diff
@@ -337,121 +337,6 @@ func TestWellKnownReverseProxy(t *testing.T) {
 	})
 }
 
-func TestWellKnownHeaderPropagation(t *testing.T) {
```
Comment (matzew) [inline pkg/http/http_test.go:340]: nice to move out to dedicated file!

File: pkg/http/wellknown.go (hunk 1 above)
Comment (manusa) [reply pkg/http/wellknown.go:96]: I personally don't like the helper method approach in this case. It's a function with side-effects and doesn't really simplify things (in this case we're replacing 3 quite semantic lines with 6 lines with an ad-hoc method that isn't reused elsewhere).

Nonetheless, I added a subsequent commit with these changes ;)

File: pkg/http/http_test.go (hunk 2 above)
Comment (manusa) [reply pkg/http/http_test.go:340]: I'll follow up with further refactor to move the entire suite to testify. Some tech debt pending for weeks now.

**Comment by matzew** [comment]
Great!

LGTM

**Comment by Cali0707** [comment]
@manusa when I tried running with this code I saw CORS failed errors from the inspector with firefox (and could not get the OAuth flow to work):

Screenshot 2026-01-09 at 08 47 12

**Comment by manusa** [comment]
hmm, didn't try this one with Firefox, let me give it a spin. Was working fine from Chrome.

**Comment by manusa** [comment]
> @manusa when I tried running with this code I saw CORS failed errors from the inspector with firefox (and could not get the OAuth flow to work):
> 
> Screenshot 2026-01-09 at 08 47 12

Was this working in firefox before? I notice that Firefox is performing an HTTP**S** connection as opposed to Chrome.

**Comment by Cali0707** [comment]
> Was this working in firefox before? I notice that Firefox is performing an HTTP**S** connection as opposed to Chrome.

@manusa it seems to not be working in firefox with code built from `main` either -  however back when we tested this before (when we did the initial CORS fix) it did work there. Probably some combo of newer firefox version/newer MCP inspector version...

**Comment by manusa** [comment]
> > Was this working in firefox before? I notice that Firefox is performing an HTTP**S** connection as opposed to Chrome.
> 
> @manusa it seems to not be working in firefox with code built from `main` either - however back when we tested this before (when we did the initial CORS fix) it did work there. Probably some combo of newer firefox version/newer MCP inspector version...

OK, I'm having a complicated day today.

I had wrong settings in Firefox and also tried to perform the client registration from the inspector (which won't work).


I'm using Firefox 140.6.0esr (macOS).

The flow works correctly with some nuances:
- You need to first go into the keycloak HTTPS web interface to add the self-signed certificate exception
- You need to set the Client ID to `mcp-client` otherwise, client registration is attempted and won't work (same CORS issue, should not be a problem with conventional MCP clients/hosts)
  Client Registration also fails in Chrome.

If the settings are fine, everything should work:

image

**Comment by Cali0707** [comment]
@manusa for setting that exception in the UI - let's see if we can add that into the keycloak setup in a separate PR

**Comment by manusa** [comment]
> @manusa for setting that exception in the UI - let's see if we can add that into the keycloak setup in a separate PR

I didn't explain this correctly.

It's not something you add to keycloak.

It's an exception you add to Firefox to acknowledge the security risk of accessing a TLS protected site with a self-signed certificate (not present in the local CA list):

image

`Accept the Risk and Continue`

image
